name: Build, Run, and Upload Parsed Results

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'  # Adjust the Go version as needed

      - name: Initialize Go Module
        run: |
          go mod init checker || true
          go mod tidy

      - name: Build the Program
        run: go build -o search search.go

      - name: Run the Scraper
        run: ./search

      - name: Upload CSV Artifact
        uses: actions/upload-artifact@v3
        with:
          name: parsed-results
          path: linkedin_candidates.csv
